version: "3.8"

networks:
    monitor:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: monitor-nginx
        ports:
            - "3456:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - monitor
    mysql:
        image: mysql:5.7
        container_name: monitor-mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3307:3306"
        volumes:
            - ./storage/app/docker/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: 'monitor'
            MYSQL_USER: 'monitor'
            MYSQL_PASSWORD: 'monitor'
            MYSQL_ROOT_PASSWORD: 'monitor'
        networks:
            - monitor
    php:
        build:
            args:
                user: 'monitor'
                uid: ${DOCKER_UID}
            context: ./docker/php
            dockerfile: ./Dockerfile
        container_name: monitor-php
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./docker/php/php-cli.ini:/usr/local/etc/php/php-cli.ini
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - mysql
        networks:
            - monitor
    cron:
        build:
            args:
                main_user: 'monitor'
                user: 'monitor'
                uid: ${DOCKER_UID}
            context: ./docker/php
            dockerfile: ./Dockerfile
        container_name: monitor-cron
        working_dir: /var/www/html
        entrypoint: './docker/cron/loop.sh'
        volumes:
            - ./:/var/www/html
            - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        depends_on:
            - php
        networks:
            - monitor
